# Product sigma-algebras -- the check behind the card.  Standard library only.
# Part 1: a coarse scoring machine on six cells of the dartboard; every family
# is listed and the product sigma-algebra is built by three roads.  Part 2:
# slices of the disc of radius 0.5 m, by formula and by an exact integer scan.
# Part 3: the disc as a union of grid squares, counted by corners and by slices.
# The code checks instances and finite stages; the proofs cover every set.
COLS, ROWS = ["L", "M", "R"], ["bottom", "top"]
F1 = [0b000, 0b001, 0b110, 0b111]   # the machine tells column L from M-or-R, no more
F2 = [0b00, 0b01, 0b10, 0b11]       # it tells the bottom half from the top half
FULL = 63                           # a set of cells is a 6-bit mask; cell (i, j) is bit 2i + j

def rect(A, B):                     # the rectangle A x B, as a set of cells
    return sum(1 << (2 * i + j) for i in range(3) for j in range(2) if A >> i & 1 and B >> j & 1)

def closure(C):                     # add complements and unions until nothing new
    S = set(C) | {0}
    while True:
        new = S | {FULL ^ m for m in S} | {a | b for a in S for b in S}
        if new == S:
            return S
        S = new

def xsec(E, i):                     # the slice of E at column i: the rows it hits there
    return sum(1 << j for j in range(2) if E >> (2 * i + j) & 1)

def ysec(E, j):                     # the slice of E at row j: the columns it hits there
    return sum(1 << i for i in range(3) if E >> (2 * i + j) & 1)

def show(E):
    return "{" + ", ".join(f"{COLS[i]}-{ROWS[j]}" for i in range(3) for j in range(2) if E >> (2 * i + j) & 1) + "}"

def atoms(F):                       # smallest nonempty members of a finite sigma-algebra
    return [a for a in F if a and not any(b and b != a and a & b == b for b in F)]

yn = lambda c: "yes" if c else "no"
rects = {rect(A, B) for A in F1 for B in F2}
road1 = closure(rects)                                           # generated by rectangles
road2 = closure({rect(A, 3) for A in F1} | {rect(7, B) for B in F2})  # by strips: one coordinate asked
cells = [rect(a, b) for a in atoms(F1) for b in atoms(F2)]
road3 = {sum(c for k, c in enumerate(cells) if s >> k & 1) for s in range(1 << len(cells))}
good = {E for E in range(64)
        if all(xsec(E, i) in F2 for i in range(3)) and all(ysec(E, j) in F1 for j in range(2))}
stair = rect(0b001, 0b01) | rect(0b110, 0b10)
single = rect(0b010, 0b01)
print(f"scoring machine: 6 cells, 64 subsets; F1 has {len(F1)} sets, F2 has {len(F2)} sets")
print(f"distinct rectangles A x B: {len(rects)}")
print(f"product sigma-algebra: from rectangles {len(road1)}, from strips {len(road2)}, from atom cells {len(road3)}")
print("atom cells: " + " | ".join(show(c) for c in sorted(cells)))
print(f"staircase {show(stair)}: in product {yn(stair in road1)}, a rectangle {yn(stair in rects)}")
print(f"single cell {show(single)}: in product {yn(single in road1)}; "
      f"its slice at bottom is {{M}}, allowed by F1 {yn(ysec(single, 0) in F1)}")
print(f"subsets whose every slice is allowed: {len(good)}; every product set among them: {yn(road1 <= good)}")
assert road1 == road2 == road3 and len(road1) == 16            # three roads, one family
assert road1 <= good and single not in road1                    # slices of product sets are allowed
assert len(rects) == 10 and stair in road1 and stair not in rects

# ---- Part 2: slices of the disc (x - 0.5)^2 + (y - 0.5)^2 <= 0.25 on the 1 m board ----
def sqrt(v):                        # Newton's method, written out
    if v <= 0:
        return 0.0
    r = max(v, 1.0)
    for _ in range(80):
        r = (r + v / r) / 2
    return r

N = 10000                           # the scan: y = K / N, integers only
for X in [2000, 5000, 8000, 9500, 10000]:
    x = X / N
    h = sqrt(0.25 - (x - 0.5) ** 2)                          # formula: half-width of the slice
    inside = [K for K in range(N + 1) if (X - 5000) ** 2 + (K - 5000) ** 2 <= 5000 ** 2]
    lo, hi = inside[0] / N, inside[-1] / N
    assert abs(lo - (0.5 - h)) <= 1 / N and abs(hi - (0.5 + h)) <= 1 / N
    print(f"x = {x:.3f}: slice by formula [{0.5 - h:.4f}, {0.5 + h:.4f}], length {2 * h:.4f}; "
          f"by integer scan [{lo:.4f}, {hi:.4f}]")
d2 = (0.2 - 0.5) ** 2
print(f"by hand, x = 0.2: distance from centre {0.5 - 0.2:.1f}, (0.2 - 0.5)^2 = {d2:.2f}, 0.25 - {d2:.2f} = {0.25 - d2:.2f}, half-width {sqrt(0.25 - d2):.1f}")

# ---- Part 3: grid squares of side 1/n inside the open disc ----
def isqrt(m):                       # largest t with t*t <= m, integers only
    t = m
    while t * t > m:
        t = (t + m // t) // 2
    return t

s = 0.0                           # pi/4 by Machin: 4 arctan(1/5) - arctan(1/239)
for q, w in [(5, 4), (239, -1)]:
    for i in range(40):
        s += w * (-1) ** i / ((2 * i + 1) * q ** (2 * i + 1))
quarter_pi = s
print(f"disc area pi/4 = {quarter_pi:.6f} (Machin series)")
cols8 = []
for n in [2, 4, 8, 16, 32, 64, 128, 256, 512]:
    c, R2 = n // 2, (n // 2) ** 2   # centre and radius squared, in units of 1/n
    by_corners = sum(1 for i in range(n) for j in range(n)
                     if all((u - c) ** 2 + (v - c) ** 2 < R2 for u in (i, i + 1) for v in (j, j + 1)))
    t = [isqrt(R2 - (u - c) ** 2 - 1) if R2 - (u - c) ** 2 >= 1 else 0 for u in range(n + 1)]
    by_slices = sum(2 * min(t[i], t[i + 1]) for i in range(n))  # each column: the shorter edge slice
    area = by_corners / n ** 2
    gap, bound = quarter_pi - area, 4 * quarter_pi * sqrt(2.0) / n
    assert by_corners == by_slices and 0 < gap <= bound
    if n == 8:
        cols8 = [min(t[i], t[i + 1]) for i in range(n)]
    print(f"n = {n:3}: squares by corners {by_corners:6}, by slices {by_slices:6}, "
          f"area {area:.6f}, pi/4 - area {gap:.6f}, bound pi*sqrt2/n {bound:.6f}")
print("n = 8 column runs of squares: " + ", ".join(str(2 * t) for t in cols8 if t))
fx = lambda v: 70 + 180 * v         # the picture: 180 units per metre, origin at (70, 200)
fy = lambda v: 200 - 180 * v
print("figure, board (70, 20) to (250, 200); disc centre (%g, %g) radius %g; slice x = 0.2 at %g from y %g to %g"
      % (fx(0.5), fy(0.5), 180 * 0.5, fx(0.2), fy(0.1), fy(0.9)))
print("figure, n = 8 columns (x, top, height): " + "; ".join(
    f"{fx(i / 8):g}, {fy((4 + t) / 8):g}, {180 * 2 * t / 8:g}" for i, t in enumerate(cols8) if t))
print("ALL CHECKS PASS")
