// Product sigma-algebras -- the same check as the Python, in Rust, std only.
// Part 1: a coarse scoring machine on six cells of the dartboard; the product
// sigma-algebra built by three roads.  Part 2: slices of the disc of radius
// 0.5 m, by formula and by an exact integer scan.  Part 3: the disc as a union
// of grid squares, counted by corners and by slices.
use std::collections::BTreeSet;

const COLS: [&str; 3] = ["L", "M", "R"];
const ROWS: [&str; 2] = ["bottom", "top"];
const F1: [u32; 4] = [0b000, 0b001, 0b110, 0b111]; // tells column L from M-or-R, no more
const F2: [u32; 4] = [0b00, 0b01, 0b10, 0b11]; // tells bottom half from top half
const FULL: u32 = 63; // a set of cells is a 6-bit mask; cell (i, j) is bit 2i + j

fn rect(a: u32, b: u32) -> u32 {
    let mut m = 0;
    for i in 0..3 { for j in 0..2 { if a >> i & 1 == 1 && b >> j & 1 == 1 { m |= 1 << (2 * i + j); } } }
    m
}
// add complements and unions until nothing new
fn closure(c: &BTreeSet<u32>) -> BTreeSet<u32> {
    let mut s = c.clone();
    s.insert(0);
    loop {
        let mut new = s.clone();
        for &a in &s {
            new.insert(FULL ^ a);
            for &b in &s { new.insert(a | b); }
        }
        if new == s { return s; }
        s = new;
    }
}
fn xsec(e: u32, i: u32) -> u32 { (0..2).filter(|j| e >> (2 * i + j) & 1 == 1).map(|j| 1 << j).sum() }
fn ysec(e: u32, j: u32) -> u32 { (0..3).filter(|i| e >> (2 * i + j) & 1 == 1).map(|i| 1 << i).sum() }
fn show(e: u32) -> String {
    let mut v = vec![];
    for i in 0..3 { for j in 0..2 { if e >> (2 * i + j) & 1 == 1 { v.push(format!("{}-{}", COLS[i], ROWS[j])); } } }
    format!("{{{}}}", v.join(", "))
}
fn atoms(f: &[u32]) -> Vec<u32> {
    f.iter().copied().filter(|&a| a != 0 && !f.iter().any(|&b| b != 0 && b != a && a & b == b)).collect()
}
fn yn(c: bool) -> &'static str { if c { "yes" } else { "no" } }
fn sqrt(v: f64) -> f64 { // Newton's method, written out
    if v <= 0.0 { return 0.0; }
    let mut r = if v > 1.0 { v } else { 1.0 };
    for _ in 0..80 { r = (r + v / r) / 2.0; }
    r
}
fn isqrt(m: i64) -> i64 { // largest t with t*t <= m, integers only
    let mut t = m;
    while t * t > m { t = (t + m / t) / 2; }
    t
}

fn main() {
    let rects: BTreeSet<u32> = F1.iter().flat_map(|&a| F2.iter().map(move |&b| rect(a, b))).collect();
    let road1 = closure(&rects); // generated by rectangles
    let strips: BTreeSet<u32> = F1.iter().map(|&a| rect(a, 3)).chain(F2.iter().map(|&b| rect(7, b))).collect();
    let road2 = closure(&strips); // by strips: one coordinate asked
    let mut cells: Vec<u32> = vec![];
    for &a in &atoms(&F1) { for &b in &atoms(&F2) { cells.push(rect(a, b)); } }
    let road3: BTreeSet<u32> = (0..1u32 << cells.len())
        .map(|s| (0..cells.len()).filter(|k| s >> k & 1 == 1).map(|k| cells[k]).sum()).collect();
    let good: BTreeSet<u32> = (0..64)
        .filter(|&e| (0..3).all(|i| F2.contains(&xsec(e, i))) && (0..2).all(|j| F1.contains(&ysec(e, j)))).collect();
    let stair = rect(0b001, 0b01) | rect(0b110, 0b10);
    let single = rect(0b010, 0b01);
    cells.sort();
    println!("scoring machine: 6 cells, 64 subsets; F1 has {} sets, F2 has {} sets", F1.len(), F2.len());
    println!("distinct rectangles A x B: {}", rects.len());
    println!("product sigma-algebra: from rectangles {}, from strips {}, from atom cells {}", road1.len(), road2.len(), road3.len());
    let a: Vec<String> = cells.iter().map(|&c| show(c)).collect();
    println!("atom cells: {}", a.join(" | "));
    println!("staircase {}: in product {}, a rectangle {}", show(stair), yn(road1.contains(&stair)), yn(rects.contains(&stair)));
    println!("single cell {}: in product {}; its slice at bottom is {{M}}, allowed by F1 {}",
             show(single), yn(road1.contains(&single)), yn(F1.contains(&ysec(single, 0))));
    println!("subsets whose every slice is allowed: {}; every product set among them: {}", good.len(), yn(road1.is_subset(&good)));
    assert!(road1 == road2 && road2 == road3 && road1.len() == 16); // three roads, one family
    assert!(road1.is_subset(&good) && !road1.contains(&single)); // slices of product sets are allowed
    assert!(rects.len() == 10 && road1.contains(&stair) && !rects.contains(&stair));

    // ---- Part 2: slices of the disc (x - 0.5)^2 + (y - 0.5)^2 <= 0.25 on the 1 m board ----
    let n_scan: i64 = 10000; // the scan: y = K / N, integers only
    for xi in [2000i64, 5000, 8000, 9500, 10000] {
        let x = xi as f64 / n_scan as f64;
        let h = sqrt(0.25 - (x - 0.5) * (x - 0.5)); // formula: half-width of the slice
        let inside: Vec<i64> = (0..=n_scan).filter(|k| (xi - 5000).pow(2) + (k - 5000).pow(2) <= 5000 * 5000).collect();
        let (lo, hi) = (inside[0] as f64 / n_scan as f64, inside[inside.len() - 1] as f64 / n_scan as f64);
        assert!((lo - (0.5 - h)).abs() <= 1.0 / n_scan as f64 && (hi - (0.5 + h)).abs() <= 1.0 / n_scan as f64);
        println!("x = {:.3}: slice by formula [{:.4}, {:.4}], length {:.4}; by integer scan [{:.4}, {:.4}]",
                 x, 0.5 - h, 0.5 + h, 2.0 * h, lo, hi);
    }
    let d2 = (0.2f64 - 0.5).powi(2);
    println!("by hand, x = 0.2: distance from centre {:.1}, (0.2 - 0.5)^2 = {:.2}, 0.25 - {:.2} = {:.2}, half-width {:.1}", 0.5 - 0.2, d2, d2, 0.25 - d2, sqrt(0.25 - d2));

    // ---- Part 3: grid squares of side 1/n inside the open disc ----
    let mut s = 0.0f64; // pi/4 by Machin: 4 arctan(1/5) - arctan(1/239)
    for (q, w) in [(5.0f64, 4.0f64), (239.0, -1.0)] {
        for i in 0..40 { s += w * (-1.0f64).powi(i) / ((2 * i + 1) as f64 * q.powi(2 * i + 1)); }
    }
    let quarter_pi = s;
    println!("disc area pi/4 = {:.6} (Machin series)", quarter_pi);
    let mut cols8: Vec<i64> = vec![];
    for n in [2i64, 4, 8, 16, 32, 64, 128, 256, 512] {
        let (c, r2) = (n / 2, (n / 2) * (n / 2)); // centre and radius squared, in units of 1/n
        let mut by_corners = 0i64;
        for i in 0..n { for j in 0..n {
            let ok = [i, i + 1].iter().all(|&u| [j, j + 1].iter().all(|&v| (u - c).pow(2) + (v - c).pow(2) < r2));
            if ok { by_corners += 1; }
        } }
        let t: Vec<i64> = (0..=n).map(|u| { let m = r2 - (u - c).pow(2); if m >= 1 { isqrt(m - 1) } else { 0 } }).collect();
        let by_slices: i64 = (0..n as usize).map(|i| 2 * t[i].min(t[i + 1])).sum(); // the shorter edge slice
        let area = by_corners as f64 / (n * n) as f64;
        let (gap, bound) = (quarter_pi - area, 4.0 * quarter_pi * sqrt(2.0) / n as f64);
        assert!(by_corners == by_slices && 0.0 < gap && gap <= bound);
        if n == 8 { cols8 = (0..8).map(|i| t[i].min(t[i + 1])).collect(); }
        println!("n = {:3}: squares by corners {:6}, by slices {:6}, area {:.6}, pi/4 - area {:.6}, bound pi*sqrt2/n {:.6}",
                 n, by_corners, by_slices, area, gap, bound);
    }
    let runs: Vec<String> = cols8.iter().filter(|&&t| t > 0).map(|t| (2 * t).to_string()).collect();
    println!("n = 8 column runs of squares: {}", runs.join(", "));
    let fx = |v: f64| 70.0 + 180.0 * v; // the picture: 180 units per metre, origin at (70, 200)
    let fy = |v: f64| 200.0 - 180.0 * v;
    println!("figure, board (70, 20) to (250, 200); disc centre ({}, {}) radius {}; slice x = 0.2 at {} from y {} to {}",
             fx(0.5), fy(0.5), 180.0 * 0.5, fx(0.2), fy(0.1), fy(0.9));
    let cs: Vec<String> = cols8.iter().enumerate().filter(|(_, &t)| t > 0)
        .map(|(i, &t)| format!("{}, {}, {}", fx(i as f64 / 8.0), fy((4 + t) as f64 / 8.0), 180.0 * 2.0 * t as f64 / 8.0)).collect();
    println!("figure, n = 8 columns (x, top, height): {}", cs.join("; "));
    println!("ALL CHECKS PASS");
}
